# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class HelloCli < Formula
  desc ""
  homepage ""
  version "0.2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/DaisukeKarasawa/hello-cli/releases/download/v0.2.0/hello-cli_Darwin_x86_64.tar.gz"
      sha256 "9389ec306bb51499f3246be4e0467be64fe1dbd9804fa41836a945aaddb074d0"

      def install
        bin.install "hello-cli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/DaisukeKarasawa/hello-cli/releases/download/v0.2.0/hello-cli_Darwin_arm64.tar.gz"
      sha256 "acd9ee55c16ed59673ccff59ad152f39550cf8efb1ae6081de9b053abec24e02"

      def install
        bin.install "hello-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/DaisukeKarasawa/hello-cli/releases/download/v0.2.0/hello-cli_Linux_x86_64.tar.gz"
        sha256 "a60728d35e7a8d5db76b0184942289c80326796750bc46d10f2e04ad6b32e34f"

        def install
          bin.install "hello-cli"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/DaisukeKarasawa/hello-cli/releases/download/v0.2.0/hello-cli_Linux_arm64.tar.gz"
        sha256 "5838db370d12932d8c73305ae397133acb54e76704f5c5669cfe58f87033bb4c"

        def install
          bin.install "hello-cli"
        end
      end
    end
  end
end
